# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Configuration-wide default for the stages property of hooks.
default_stages: [commit, push]
# This exclude migration and __init__.py files
exclude: ^([a-zA-Z]*/(migrations)/(.)*|__init__.py)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # Identify invalid files
      # check whether the files parse as valid python.
      - id: check-ast
      # checks yaml files for parseable syntax.
      - id: check-yaml

      # General quality checks
      # trims trailing whitespace.
      - id: trailing-whitespace
      # replaces or checks mixed line ending
      - id: mixed-line-ending
      # ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer

      # Python checks
      # check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: debug-statements
      # verifies that test files are named correctly
      - id: name-tests-test
        args: [ "--django" ]

      # Git checks
      # detects the presence of private keys
      - id: detect-private-key
      # check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # prevent giant files from being committed
      - id: check-added-large-files

  # Removes unused imports and unused variables
  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        args:
            [
                "--in-place",
                "--remove-all-unused-imports",
                "--remove-unused-variables",
                "--expand-star-imports",
                "--remove-duplicate-keys",
                "--ignore-init-module-imports",
            ]
  # Sort imports alphabetically, and automatically separated into sections and by type
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        # Uses max line length to 88 chars
        args: ["--line-length=88", --safe, --quiet]
