"""Add Absentee model

Revision ID: 0e9e87f286be
Revises: be43cd401d59
Create Date: 2022-10-24 01:35:22.278599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9e87f286be'
down_revision = 'be43cd401d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absentee',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('absent_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'absent_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absentee')
    # ### end Alembic commands ###
